-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."dimProduct"
(
    "productID" character varying NOT NULL,
    "productName" character varying,
    "productGroup" character varying,
    "productLine" character varying,
    "productCategory" character varying,
    "supplierID" character varying,
    PRIMARY KEY ("productID")
);

CREATE TABLE IF NOT EXISTS public."dimCustomerStatus"
(
    "customerStatusID" character varying NOT NULL,
    "customerID" character varying,
    "customerStatus" character varying,
    PRIMARY KEY ("customerStatusID")
);

CREATE TABLE IF NOT EXISTS public."factOrder"
(
    "orderID" character varying NOT NULL,
    "orderPrice" double precision,
    "costPerProduct" double precision,
    "orderQuantity" integer,
    "orderDate" date,
    "deliveryDate" date,
    "customerStatusID" character varying,
    "productID" character varying,
    PRIMARY KEY ("orderID")
);

CREATE TABLE IF NOT EXISTS public."dimDate"
(
    date date NOT NULL,
    day integer,
    month integer,
    quarter integer,
    year integer,
    PRIMARY KEY (date)
);

CREATE TABLE IF NOT EXISTS public."dimSupplier"
(
    "supplierID" character varying NOT NULL,
    "supplierName" character varying,
    "supplierCountryID" character varying,
    PRIMARY KEY ("supplierID")
);

CREATE TABLE IF NOT EXISTS public."dimCountry"
(
    "countryID" character varying NOT NULL,
    "countryName" character varying,
    PRIMARY KEY ("countryID")
);

CREATE TABLE IF NOT EXISTS public."dimCustomer"
(
    "customerID" character varying NOT NULL,
    PRIMARY KEY ("customerID")
);

ALTER TABLE IF EXISTS public."dimProduct"
    ADD FOREIGN KEY ("supplierID")
    REFERENCES public."dimSupplier" ("supplierID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."dimCustomerStatus"
    ADD FOREIGN KEY ("customerID")
    REFERENCES public."dimCustomer" ("customerID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."factOrder"
    ADD FOREIGN KEY ("productID")
    REFERENCES public."dimProduct" ("productID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."factOrder"
    ADD FOREIGN KEY ("customerStatusID")
    REFERENCES public."dimCustomerStatus" ("customerStatusID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."factOrder"
    ADD FOREIGN KEY ("orderDate")
    REFERENCES public."dimDate" (date) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."factOrder"
    ADD FOREIGN KEY ("deliveryDate")
    REFERENCES public."dimDate" (date) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."dimSupplier"
    ADD FOREIGN KEY ("supplierCountryID")
    REFERENCES public."dimCountry" ("countryID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;