-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."dimDate"
(
    "dateID" character varying NOT NULL,
    "orderDate" date,
    month integer,
    "montName" character varying,
    year integer,
    quarter integer,
    "quarterName" character varying,
    day integer,
    "dayOfWeek" integer,
    "dayOfWeekName" character varying,
    PRIMARY KEY ("dateID")
);

CREATE TABLE IF NOT EXISTS public."dimProduct"
(
    "productID" character varying NOT NULL,
    "productName" character varying,
    "productGroupID" character varying,
    "productCategoryID" character varying,
    PRIMARY KEY ("productID")
);

CREATE TABLE IF NOT EXISTS public."dimGroup"
(
    "groupID" character varying NOT NULL,
    "groupName" character varying,
    PRIMARY KEY ("groupID")
);

CREATE TABLE IF NOT EXISTS public."dimCountry"
(
    "countryID" character varying NOT NULL,
    "countryName" character varying,
    PRIMARY KEY ("countryID")
);

CREATE TABLE IF NOT EXISTS public."dimSupplier"
(
    "supplierID" character varying NOT NULL,
    "supplierName " character varying,
    "countryID" character varying,
    PRIMARY KEY ("supplierID")
);

CREATE TABLE IF NOT EXISTS public."dimStatus"
(
    "statusID" character varying NOT NULL,
    "statusName " character varying,
    PRIMARY KEY ("statusID")
);

CREATE TABLE IF NOT EXISTS public."dimCustomer"
(
    "customerID" character varying NOT NULL,
    "statusID " character varying,
    PRIMARY KEY ("customerID")
);

CREATE TABLE IF NOT EXISTS public."factOrder"
(
    "orderID" character varying NOT NULL,
    "orderPrice" double precision,
    "costPerProduct" double precision,
    "orderQuantity" integer,
    "dateID" character varying,
    "customerID" character varying,
    "productID" character varying,
    "supplierID" character varying,
    PRIMARY KEY ("orderID")
);

CREATE TABLE IF NOT EXISTS public."dimCategory"
(
    "categoryID" character varying NOT NULL,
    "categoryName" character varying,
    PRIMARY KEY ("categoryID")
);

ALTER TABLE IF EXISTS public."dimProduct"
    ADD FOREIGN KEY ("productGroupID")
    REFERENCES public."dimGroup" ("groupID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."dimProduct"
    ADD FOREIGN KEY ("productCategoryID")
    REFERENCES public."dimCategory" ("categoryID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."dimSupplier"
    ADD FOREIGN KEY ("countryID")
    REFERENCES public."dimCountry" ("countryID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."dimCustomer"
    ADD FOREIGN KEY ("statusID ")
    REFERENCES public."dimStatus" ("statusID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."factOrder"
    ADD FOREIGN KEY ("dateID")
    REFERENCES public."dimDate" ("dateID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."factOrder"
    ADD FOREIGN KEY ("productID")
    REFERENCES public."dimProduct" ("productID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."factOrder"
    ADD FOREIGN KEY ("supplierID")
    REFERENCES public."dimSupplier" ("supplierID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."factOrder"
    ADD FOREIGN KEY ("customerID")
    REFERENCES public."dimCustomer" ("customerID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;